pub mod bmp;
pub mod helpers;
pub mod test_blend_modes;
pub mod test_custom_shader;
pub mod test_draw_dynamic;
pub mod test_draw_static;
pub mod test_init_shutdown;
pub mod test_multitexturing;
pub mod test_png_loading;